# Generated by Django 5.2.9 on 2026-01-05 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_rename_quantity_reserved_inventory_reserved_quantity_and_more",
        ),
        ("org", "0002_alter_department_unique_together_and_more"),
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="auditlog",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="store",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="verified_by",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="description",
            field=models.TextField(default="2. commit"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="hod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_requisitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="priority",
            field=models.CharField(default="normal", max_length=20),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisitions",
                to="org.department",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisitions",
                to="inventory.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisitions",
                to="org.organization",
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_requisitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("requested", "Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("reserved", "Reserved"),
                    ("delivered", "Delivered"),
                    ("verified", "Verified"),
                    ("completed", "Completed"),
                ],
                default="requested",
                max_length=20,
            ),
        ),
    ]
