# Generated by Django 5.2.9 on 2026-01-05 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "organization")},
        ),
        migrations.RemoveField(
            model_name="organization",
            name="email_domain",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="department",
            name="code",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="organization",
            name="code",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name="department",
            name="is_active",
        ),
    ]
