# Generated by Django 5.2.9 on 2026-01-05 00:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="quantity_reserved",
            new_name="reserved_quantity",
        ),
        migrations.AlterUniqueTogether(
            name="item",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("item", "store")},
        ),
        migrations.RemoveField(
            model_name="store",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="store",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="store",
            name="store_type",
        ),
        migrations.AddField(
            model_name="inventory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="store",
            name="is_vendor",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventories",
                to="inventory.store",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="reference",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="sku",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="store",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="item",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="inventory",
            name="organization",
        ),
        migrations.CreateModel(
            name="VendorItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("lead_time_days", models.PositiveIntegerField(default=0)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_items",
                        to="inventory.item",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_items",
                        to="inventory.store",
                    ),
                ),
            ],
            options={
                "unique_together": {("vendor", "item")},
            },
        ),
    ]
