# Generated by Django 5.2.9 on 2026-01-05 02:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_rename_quantity_reserved_inventory_reserved_quantity_and_more",
        ),
        ("org", "0003_alter_department_options_alter_organization_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("low_stock", "Low Stock"),
                            ("expiry", "Near Expiry"),
                            ("out_of_stock", "Out of Stock"),
                            ("over_stock", "Over Stock"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={"ordering": ["item__name"]},
        ),
        migrations.AlterModelOptions(
            name="inventorymovement",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="store",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="vendoritem",
            options={"ordering": ["item__name"]},
        ),
        migrations.RemoveField(
            model_name="inventorymovement",
            name="reference",
        ),
        migrations.AddField(
            model_name="inventory",
            name="batch_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="inventory",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="location",
            field=models.CharField(
                blank=True, help_text="e.g., Shelf A1, Room 101", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="maximum_quantity",
            field=models.PositiveIntegerField(
                default=1000, help_text="Maximum stock capacity"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="minimum_quantity",
            field=models.PositiveIntegerField(
                default=10, help_text="Reorder threshold"
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("low_stock", "Low Stock"),
                    ("out_of_stock", "Out of Stock"),
                    ("expired", "Expired"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="destination_store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_transfers",
                to="inventory.store",
            ),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="source_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="inventorymovement",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("requisition", "Requisition"),
                    ("purchase_order", "Purchase Order"),
                    ("transfer_order", "Transfer Order"),
                    ("stock_take", "Stock Take"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="item",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="item",
            name="unit_of_measure",
            field=models.CharField(default="units", max_length=20),
        ),
        migrations.AddField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="store",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="store",
            name="code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="store",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="store",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="store",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stores",
                to="org.department",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="store",
            name="store_type",
            field=models.CharField(
                choices=[
                    ("internal", "Internal Store"),
                    ("vendor", "External Vendor"),
                    ("ward", "Hospital Ward"),
                    ("clinic", "Clinic"),
                ],
                default="internal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="vendoritem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vendoritem",
            name="currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
        migrations.AddField(
            model_name="vendoritem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vendoritem",
            name="minimum_order_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="vendoritem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="quantity_available",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="reserved_quantity",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("stock_in", "Stock In"),
                    ("stock_out", "Stock Out"),
                    ("reserve", "Reserve"),
                    ("release", "Release"),
                    ("adjustment", "Adjustment"),
                    ("transfer", "Transfer"),
                    ("write_off", "Write Off"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inventorymovement",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="store",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="store",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="vendoritem",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="vendoritem",
            name="lead_time_days",
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="vendoritem",
            name="vendor",
            field=models.ForeignKey(
                limit_choices_to={"store_type": "vendor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_items",
                to="inventory.store",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="store",
            unique_together={("organization", "code")},
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["item", "store"], name="inventory_i_item_id_da4e72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["store", "status"], name="inventory_i_store_i_e9475b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(
                fields=["expiry_date"], name="inventory_i_expiry__faeaca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["inventory", "created_at"],
                name="inventory_i_invento_4ccb95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["movement_type", "created_at"],
                name="inventory_i_movemen_7bd8e8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorymovement",
            index=models.Index(
                fields=["performed_by", "created_at"],
                name="inventory_i_perform_915302_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["organization", "sku"], name="inventory_i_organiz_6ca2ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["organization", "category"],
                name="inventory_i_organiz_cbae84_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["organization", "store_type"],
                name="inventory_s_organiz_4f33b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["organization", "is_active"],
                name="inventory_s_organiz_1b9175_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vendoritem",
            index=models.Index(
                fields=["vendor", "item"], name="inventory_v_vendor__ac1d66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vendoritem",
            index=models.Index(
                fields=["is_active"], name="inventory_v_is_acti_2b68ef_idx"
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="inventory.inventory",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["inventory", "is_resolved"],
                name="inventory_s_invento_d8c58e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockalert",
            index=models.Index(
                fields=["alert_type", "created_at"],
                name="inventory_s_alert_t_8991f4_idx",
            ),
        ),
    ]
